---

 - name: Use template datasource.j2
   template:
    src: /etc/ansible/roles/Prometheus-Grafana/templates/datasource.j2
    dest: /etc/grafana/provisioning/datasources/datasource.yml

 - name: Create Dashboard directory to store the dashboard json file
   file:
    path: /etc/grafana/dashboard
    state: directory

 - name: Copy the template dashboard file to add in dashboard tab
   copy:
    src: /etc/ansible/roles/Prometheus-Grafana/files/dashboard.json
    dest: /etc/grafana/dashboard/dashboard.json

 - name: Remove sample.yml file
   file:
    path: /etc/grafana/provisioning/dashboards/sample.yml
    state: absent

 - name: Copy Sample.yml file to include dashboard 
   copy:
    src: /etc/ansible/roles/Prometheus-Grafana/files/sample.yml
    dest: /etc/grafana/provisioning/dashboards
   notify:
    - Restart Grafana

