---

 - name: Update and Upgrade host
   apt:
    update_cache: yes
    upgrade: yes

 - name: Install Prometheus
   apt:
    name: prometheus
    state: latest

 - name: Add an apt signing key
   apt_key:
    state: present
    url: https://packages.grafana.com/gpg.key

 - name: Add repository for stable releases
   lineinfile:
    line: "deb https://packages.grafana.com/enterprise/deb stable main"
    dest: /etc/apt/sources.list

 - name: Install Grafana
   apt:
    name: grafana
    state: latest

 - name: Restart Grafana
   service:
    name: grafana-server
    state: restarted
