{
 "title": "System metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without(cpu) (irate(node_cpu{job=\"node\",instance=\"localhost:9100\", mode!=\"idle\"}[1m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=\"localhost:9100\",job=\"node\"} - node_memory_MemFree{instance=\"localhost:9100\",job=\"node\"} - node_memory_Cached{instance=\"localhost:9100\",job=\"node\"} - node_memory_Buffers{instance=\"localhost:9100\",job=\"node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers{instance=\"localhost:9100\",job=\"node\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_MemFree{instance=\"localhost:9100\",job=\"node\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Cached{instance=\"localhost:9100\",job=\"node\"}",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "Available Disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail{job=\"node\",instance=\"localhost:9100\",device!~\"/dev/loop.*\",device!~\"tmpfs | nsfs\",device!=\"gvfsd-fuse\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size{job=\"node\",instance=\"localhost:9100\",device!~\"/dev/loop.*\",device!~\"tmpfs | nsfs\", device!=\"gvfsd-fuse\"} - node_filesystem_avail{job=\"node\",instance=\"localhost:9100\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes{job=\"node\",instance=\"localhost:9100\"}[5m])",
     "legendFormat": "{{device}} receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes{job=\"node\",instance=\"localhost:9100\"}[5m])",
     "legendFormat": "{{device}} transmit"
    }
   ]
  }
 ]
}